# Generated by Django 3.2.5 on 2022-02-22 19:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('CryptoCurrency', 'CryptoCurrency'), ('Art', 'Art'), ('Travel', 'Travel'), ('Health', 'Health'), ('Food', 'Food'), ('Nature', 'Nature'), ('Gaming', 'Gaming')], max_length=100)),
                ('image', models.ImageField(upload_to='Article/images')),
                ('description', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, choices=[('MainContent', 'MainContent'), ('SubContent', 'SubContent'), ('News', 'News'), ('TopPost', 'TopPost'), ('Popular', 'Popular')], max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Posts.post')),
            ],
        ),
    ]
