# Generated by Django 3.2.5 on 2021-08-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('MainContent', 'MainContent'), ('SubContent', 'SubContent'), ('News', 'News'), ('TopPost', 'TopPost')], max_length=200),
        ),
    ]
