# Generated by Django 3.2.5 on 2022-02-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
