# Generated by Django 3.2.5 on 2021-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Art', 'Art'), ('Travel', 'Travel'), ('Health', 'Health'), ('Food', 'Food')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('MainContent', 'MainContent'), ('SubContent', 'SubContent'), ('News', 'News'), ('TopPost', 'TopPost'), ('Popular', 'Popular')], max_length=200),
        ),
    ]
