# Generated by Django 3.2.5 on 2021-08-13 22:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20210812_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Art', 'Art'), ('Travel', 'Travel'), ('Health', 'Health'), ('Food', 'Food'), ('Nature', 'Nature'), ('Gaming', 'Gaming')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
