# Generated by Django 3.2.5 on 2022-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Breaking News', 'Breaking News'), ('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('CryptoCurrency', 'CryptoCurrency'), ('Art', 'Art'), ('Travel', 'Travel'), ('Health', 'Health'), ('Food', 'Food'), ('Nature', 'Nature'), ('Gaming', 'Gaming')], max_length=100),
        ),
    ]
