# Generated by Django 3.2.5 on 2022-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('CryptoCurrency', 'CryptoCurrency'), ('Art', 'Art'), ('Travel', 'Travel'), ('Health', 'Health'), ('Food', 'Food'), ('Nature', 'Nature'), ('Gaming', 'Gaming')], max_length=100),
        ),
    ]
