# Generated by Django 3.2.5 on 2021-10-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
